name: Auto Parse github form - master
run-name: ${{ github.actor }} - issue:${{ github.event.issue.number }}
on:
  issues:
    types:
      - opened
      - edited
      - labeled
      - reopened
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.ORG_PROJECT_PAT }}
  GH_REPO: ${{ github.repository }}
  NUMBER: ${{ github.event.issue.number }}
permissions:
  id-token: write

jobs:
  process-request:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.issue.user.login != 'renovate[bot]' && github.actor != 'hmcts-platform-operations' && !contains(github.event.issue.labels.*.name, 'cancel') && !contains(github.event.issue.labels.*.name, 'pull-request')
    steps:
      #Allows workflow to access repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          # token: ${{ env.GH_TOKEN }}
      #Get issue body
      - name: Get issue body
        id: get_issue_body
        run: |
          gh issue view --repo thomasthorntoncloud/test-auto-shutdown ${{ github.event.issue.number }} --json body | jq -r '.body' > body.txt
          sed -i "s/'//g" body.txt 
          cat body.txt
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Extract dates and exclusion
        id: extract_values
        run: |
          START_DATE=$(sed -n '/^### Skip shutdown start date/,/^###/p' body.txt | tail -n +2 | head -n -1 | tr -d '[:space:]')
          END_DATE=$(sed -n '/^### Skip shutdown end date/,/^###/p' body.txt | tail -n +2 | head -n -1 | tr -d '[:space:]')
          PAST_11PM=$(sed -n '/^### Do you need this exclusion past 11pm?/,$p' body.txt | tail -n +2 | sed '/^###/d' | xargs)
          
          echo "start_date=$START_DATE" >> $GITHUB_OUTPUT
          echo "end_date=$END_DATE" >> $GITHUB_OUTPUT
          echo "past_11pm=$PAST_11PM" >> $GITHUB_OUTPUT

      


      - name: Use extracted values
        run: |
          echo "Start Date: ${{ steps.extract_values.outputs.start_date }}"
          echo "End Date: ${{ steps.extract_values.outputs.end_date }}"
          echo "Past 11pm: ${{ steps.extract_values.outputs.past_11pm }}"

      - name: Update GitHub Project
        run: |
          # Get project ID
          PROJECT_ID=$(gh api graphql -f query='
            query($org: String!, $num: Int!) {
              organization(login: $org) { projectV2(number: $num) { id } }
            }' -f org="thomasthorntoncloud" -F num=2 -q '.data.organization.projectV2.id')

          echo "PROJECT_ID: $PROJECT_ID"

          # Get item ID
          ITEM_ID=$(gh api graphql -f query='
            query($owner: String!, $repo: String!, $number: Int!) {
              repository(owner: $owner, name: $repo) {
                issue(number: $number) {
                  projectV2Items(first: 1) {
                    nodes {
                      id
                    }
                  }
                }
              }
            }' -f owner="thomasthorntoncloud" -f repo="test-auto-shutdown" -f number=${{ github.event.issue.number }} -q '.data.repository.issue.projectV2Items.nodes[0].id')

          echo "ITEM_ID: $ITEM_ID"

          # Get field IDs
          FIELDS=$(gh api graphql -f query='
            query($projectId: ID!) {
              node(id: $projectId) {
                ... on ProjectV2 {
                  fields(first: 20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }' -f projectId=$PROJECT_ID -q '.data.node.fields.nodes')

          echo "All fields:"
          echo "$FIELDS" | jq '.'

          START_DATE_FIELD_ID=$(echo "$FIELDS" | jq -r '.[] | select(.name == "Start Date") | .id')
          END_DATE_FIELD_ID=$(echo "$FIELDS" | jq -r '.[] | select(.name == "End Date") | .id')

          echo "START_DATE_FIELD_ID: $START_DATE_FIELD_ID"
          echo "END_DATE_FIELD_ID: $END_DATE_FIELD_ID"

          # Convert dates to ISO 8601 format
          START_DATE=$(date -d "${{ steps.extract_values.outputs.start_date }}" +%Y-%m-%d)
          END_DATE=$(date -d "${{ steps.extract_values.outputs.end_date }}" +%Y-%m-%d)

          echo "START_DATE: $START_DATE"
          echo "END_DATE: $END_DATE"

          # Update Start Date
          if [ -n "$START_DATE_FIELD_ID" ]; then
            echo "Updating Start Date..."
            gh api graphql -f query='
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $date: Date!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId
                  itemId: $itemId
                  fieldId: $fieldId
                  value: { date: $date }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }' -f projectId=$PROJECT_ID -f itemId=$ITEM_ID -f fieldId=$START_DATE_FIELD_ID -f date=$START_DATE
          else
            echo "Start Date field not found"
          fi

          # Update End Date
          if [ -n "$END_DATE_FIELD_ID" ]; then
            echo "Updating End Date..."
            gh api graphql -f query='
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $date: Date!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId
                  itemId: $itemId
                  fieldId: $fieldId
                  value: { date: $date }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }' -f projectId=$PROJECT_ID -f itemId=$ITEM_ID -f fieldId=$END_DATE_FIELD_ID -f date=$END_DATE
          else
            echo "End Date field not found"
          fi

          echo "Project update completed"
        env:
          GH_TOKEN: ${{ secrets.ORG_PROJECT_PAT }}
      #Create a multiline variable so it can be read by parser
      # - name: multiline github var
      #   run: |
      #     echo 'ISSUE_BODY<<EOF' >> $GITHUB_ENV
      #     while read LINE; do
      #     echo "$LINE" >> $GITHUB_ENV;
      #     done < body.txt
      #     echo 'EOF' >> $GITHUB_ENV
      #     rm body.txt
      # #Parse issue form that trigger workflow
      # - name: Read submitted issue
      #   id: parse_issue
      #   uses: stefanbuck/github-issue-parser@v3.1.1
      #   with:
      #     issue-body: ${{ env.ISSUE_BODY }}
      #     template-path: .github/ISSUE_TEMPLATE/3-skip-auto-shutdown-request.yaml
      # #Save parsed date into environment variables
      # - name: Save parsed jsonString data
      #   run: |
      #     echo '${{ steps.parse_issue.outputs.jsonString }}' > NEW_DATA.json
      #     echo NEW_DATA=$(cat NEW_DATA.json | jq -c | jq '.form_environment |= split(",")') >> $GITHUB_ENV
      #     rm NEW_DATA.json
      #     echo GITHUB_REPO='${{ github.repository }}' >> $GITHUB_ENV
      #     echo ISSUE_NUMBER='${{ github.event.issue.number }}' >> $GITHUB_ENV